spring:
  application:
    name: react-gateway

server:
  compression:
    enabled: true

gateway:
  static-file-path: D:/sources/git/js/ai-chat-ui/dist
  default-file: index.html
  spa-path: /ui

ai:
  ollama:
    url: http://localhost:11434