spring:
  application:
    name: api-helper
  webflux:
    multipart:
      max-parts: 1
      max-disk-usage-per-part: 10MB
      max-in-memory-size: 10MB
      max-headers-size: 2MB
  codec:
    max-in-memory-size: 10MB
  datasource:
    url: jdbc:h2:~/.api-helper/db.h2
    driver-class-name: org.h2.Driver
    username: sa
    password:

server:
  compression:
    enabled: true

gateway:
  static-file-path: D:/sources/git/js/api-helper/dist
  default-file: index.html
  spa-path: /ui


