spring:
  application:
    name: react-gateway
  webflux:
    multipart:
      max-parts: 1
      max-disk-usage-per-part: 10MB
      max-in-memory-size: 10MB
      max-headers-size: 2MB
  codec:
    max-in-memory-size: 10MB

  r2dbc:
    url: r2dbc:postgresql://localhost:15432/sam?reWriteBatchedInserts=true
    username: rag
    password: rag
    name: rag
    pool:
      enabled: true
      initial-size: 10
      max-size: 10
      validation-query: select 1

server:
  compression:
    enabled: true

gateway:
  static-file-path: ${STATIC_FILE_PATH}
  default-file: index.html
  spa-path: /ui

ai:
  ollama:
    url: http://localhost:11434