spring:
  application:
    name: react-gateway
  webflux:
    multipart:
      max-parts: 1
      max-disk-usage-per-part: 10MB
      max-in-memory-size: 10MB
      max-header-size: 2MB
  codec:
    max-in-memory-size: 10MB
server:
  compression:
    enabled: true

gateway:
  static-file-path: D:/sources/git/js/ai-chat-ui/dist
  default-file: index.html
  spa-path: /ui

ai:
  ollama:
    url: http://localhost:11434